### PR TITLE
Fix #43

### LINKED ISSUE #43: MovingWindow computation fails on zarr cube
I tried to run the example of the MovingWindow from the pull request on a zarr cube and I get the following error:
```julia
julia> indims = InDims("Time",MovingWindow("Lon",1,1),window_oob_value = -9999.0)
InDims((YAXArrays.Cubes.Axes.ByName("Time"), MovingWindow(YAXArrays.Cubes.Axes.ByName("Lon"), 1, 1)), Array, (YAXArrays.DAT.AllMissing(),), -9999.0)
julia> r1 = mapCube(paltest, indims=indims, outdims=OutDims("Time")) do xout,xin
           xout[:] = xin[:,1]
       end
Error during running loop: DimensionMismatch("tried to assign 6×10×100×2 array to 31×30×100×2 destination")
ERROR: DimensionMismatch("tried to assign 6×10×100×2 array to 31×30×100×2 destination")
Stacktrace:
 [1] runLoop(::YAXArrays.DAT.DATConfig{1,1}, ::Bool) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:496
 [2] mapCube(::var"#59#60", ::Tuple{YAXArray{Union{Missing, Float32},4,DiskArrayTools.DiskArrayStack{Union{Missing, Float32},4,DiskArrays.SubDiskArray{Union{Missing, Float32},3},1},Array{CubeAxis,1}}}; max_cache::Float64, indims::InDims, outdims::OutDims, inplace::Bool, ispar::Bool, debug::Bool, include_loopvars::Bool, showprog::Bool, nthreads::Array{Int64,1}, loopchunksize::Dict{Any,Any}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:314
 [3] #mapCube#40 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:212 [inlined]
 [4] top-level scope at REPL[17]:1
```
paltest is the following cube:

[paltest.zarr.zip](https://github.com/meggart/YAXArrays.jl/files/6205952/paltest.zarr.zip)

I suspect, that this is due to the chunking or the out of memory handling, because when I convert the datacube to an in-memory data cube the computation works:
```
julia> paltestmem = YAXArray(collect(paltest.data))
YAXArray with the following dimensions
Dim_1               Axis with 51 Elements from 1 to 51
Dim_2               Axis with 32 Elements from 1 to 32
Dim_3               Axis with 100 Elements from 1 to 100
Dim_4               Axis with 2 Elements from 1 to 2
Total size: 1.25 MB


julia> typeof(paltestmem)
YAXArray{Union{Missing, Float32},4,Array{Union{Missing, Float32},4},Array{RangeAxis{Int64,S,Base.OneTo{Int64}} where S,1}}

julia> renameaxis!(paltestmem, "Dim_3" =>"Time")

julia> renameaxis!(paltestmem, "Dim_1" =>"Lon")

julia> renameaxis!(paltestmem, "Dim_2" =>"Lat")

julia> renameaxis!(paltestmem, "Dim_4" =>"Polarisation")

julia> r1mem = mapCube(paltestmem, indims=indims, outdims=OutDims("Time")) do xout,xin
           xout[:] = xin[:,1]
       end
YAXArray with the following dimensions
Time                Axis with 100 Elements from 1 to 100
Lon                 Axis with 51 Elements from 1 to 51
Lat                 Axis with 32 Elements from 1 to 32
Polarisation        Axis with 2 Elements from 1 to 2
Total size: 1.25 MB
```

### PR DESCRIPTION
**Pull request by meggart**
The problem in #43 occured when the last chunk along an axis in a Moving window operation was not complete. This should be fixed. I modified the tests to make sure moving windows are tested for such a case in the future.

### CODE REVIEW

File: src/DAT/DAT.jl [hunk 1]
```diff
@@ -577,7 +577,7 @@ function generateOutCube(::Type{T},eltype,oc::OutputCube,loopcachesize,co;kwargs
       cs = Base.setindex(cs,cc,i)
     end
   end
-  cube1, cube2 = createdataset(T, oc.allAxes; chunksize=cs, chunkoffset=co, kwargs...)
+  cube1, cube2 = createdataset(T, oc.allAxes; T = eltype, chunksize=cs, chunkoffset=co, kwargs...)
```
Comment (felixcremer) [inline src/DAT/DAT.jl:580]: The eltype variable here shadows Base.eltype, right? 
Should we rename this variable to maybe `elementtype`?
This doesn't have to happen in this pull request, I could prepare a PR to rename it consistently.

**Review by felixcremer — APPROVED** [review]
I have tested this on my example data and it works.

File: src/DAT/DAT.jl (hunk 1 above)
Comment (meggart) [reply src/DAT/DAT.jl]: Thanks I just fixed this
